### ISSUE TITLE
Compression support

### ISSUE THREAD

**Issue by dimkr** [dbohdan/jimhttp#10]
See https://github.com/msteveb/jimtcl/pull/36 - adding support for optional compression should be fairly easy:

```
for encoding in $headers(acceptEncoding):
    if (command exists $encoding) {
      body = $encoding body
      headers(contentEncoding) = $encoding
    }
```

However, ::http::make-response cannot access the request headers to determine which encodings are supported by the client, so this requires some refactoring.

**Comment by dbohdan** [comment]
A preliminary implementation based on our discussion so far is in https://github.com/dbohdan/jimhttp/tree/http-filters. Please test it with `::zlib`.

I'd like a compression filter that uses `zlib` instead of `gzip(1)` for `::http::sampleFilters`. Just paste it here if you don't want make a PR for a small code snippet.

**Comment by dimkr** [comment]
There you go:

``` diff
+    # Do GZip compression of the content using the zlib module
+    dict set sampleFilters gzipInternal {{body responseHeaders request} {
+        if {[dict exists $request acceptEncoding] &&
+                [string match *gzip* $request(acceptEncoding)]} {
+            dict set responseHeaders contentEncoding gzip
+            set body [zlib gzip "$body"]
+        }
+        return [list $body $responseHeaders]
+    }}
+    # Do Deflate compression of the content using the zlib module
+    dict set sampleFilters deflateInternal {{body responseHeaders request} {
+        if {[dict exists $request acceptEncoding] &&
+                [string match *deflate* $request(acceptEncoding)]} {
+            dict set responseHeaders contentEncoding deflate
+            set body [zlib deflate "$body"]
+        }
+        return [list $body $responseHeaders]
+    }}
```

Works great - tested with `wget --header='Accept-Encoding: gzip, deflate' -S`, with various combinations in `::http::responseFilters`.
