### ISSUE TITLE
Cannot parse empty arrays.

### ISSUE THREAD

**Issue by efrecon** [dbohdan/jimhttp#2]
The current version of the parser is not able to parse empty arrays, e.g.

```
::json::parse {{"test":[]}}
```

will fail. The following patch fixes it:

```
proc ::json::decode-array {str {numberDictArrays 0}} {
    set strInitial $str
    set result {}
    set value {}
    set i 0
    if {[string index $str 0] ne "\["} {
        error "can't parse JSON array: $strInitial"
    } else {
        set str [string range $str 1 end]
    }
    while 1 {
        # Empty array, get out from here.
        if { [string index [string trimleft $str] 0] eq "\]" } {
        set str [string range [string trimleft $str] 1 end]
        break
        }
        # Value.
        lassign [::cirrus::json::decode-value $str $numberDictArrays] value str
        set str [string trimleft $str]
        if {$numberDictArrays} {
            lappend result $i
        }
        lappend result $value

        # ","
        set sep [string index $str 0]
        set str [string range $str 1 end]
        if {$sep eq "\]"} {
            break
        } elseif {$sep ne ","} {
            error "can't parse JSON array: $strInitial"
        }
        incr i
    }
    return [list $result $str]
}
```

Sorry if the formatting got a little bit messed up. The idea is basically to peek forward for the end of the array and jump out of the loop at once. I haven't had time to test this thoroughly, so might need to do some extra thinking for corner cases.

**Comment by dbohdan** [comment]
Thanks for spotting the problem, and doubly so for the patch!

Could you issue a pull request with your changes to the code? This would ensure proper attribution of the code you've contributed and prevent any formatting or other copying/pasting problems.

**Comment by efrecon** [comment]
Done... I edited in the texteditor at github... Weird feeling... :)

**Comment by dbohdan** [comment]
...And merged. Thanks for the PR! I've also committed a test for this case.

> Weird feeling... :)

Beware: it's easy to get addicted to it. :-)
